### ISSUE TITLE
Add Atom or RSS feed

### ISSUE THREAD

**Issue by pickfire** [mrmrs/vimgifs#22]
Hi, I would really like to keep up with the newest giff, I hope that you could provide us news by using Atom or RSS feed.

**Comment by sammdec** [comment]
I believe the best way is to follow the twitter account @vimgifs but I appreciate that not everyone follows things on twitter.

If @mrmrs is cool with it, I'm happy to add it in

**Comment by mrmrs** [comment]
Sounds like a good addition. I'm up for including it, but haven't any knowledge on how to set it up.

**Comment by sammdec** [comment]
I have a branch ready to go on this once we switch to middleman
