### ISSUE TITLE
No visible gif for cd post

### ISSUE THREAD

**Issue by samburnstone** [mrmrs/vimgifs#26]
Thanks for the posts so far- I've found them really informative.

I noticed that the gif about the [`cd`](https://vimgifs.com/cd/) command wasn't displaying. It appears that it may be a problem with [cloudfront](https://d26aqo05ggejx9.cloudfront.net/changedir.gif)?

**Comment by sammdec** [comment]
This has been fixed now 👍 thanks for letting us know
