### ISSUE TITLE
Opening files on the specified line

### ISSUE THREAD

**Issue by wmonk** [mrmrs/vimgifs#9]
Hi!

Firstly vimgifs is awesome! I'd been following some of your vim guides under the writing section on your site. `:r` is my new favourite!

If you do `vim ~/dir/file.js +54` it'll open with the cursor on line 54. It seems that a standard way of describing file lines is like `~/dir/file.js:54`, but vim doesn't understand that. I'd like vim to be able to interpret `:54` like `+54`.

Hope that makes sense now!

Will

_There is a [plugin](https://github.com/bogado/file-line) that enables this behaviour, but thought i'd leave the question for reference 😄_

**Comment by mrmrs** [comment]
Ah thanks - understand now. Glad you found an answer so quickly!
